---
- hosts: vmware-inventory
  gather_facts: no
  connection: local
  tasks:
    - debug:
        msg:
          - "123"
          - "{{ item }}"
      with_inventory_hostnames:
        - vcenter_app
